### PR TITLE
Feat: Run E2E tests on generated release zip

### LINKED ISSUE #126: Run E2E tests on the zip generated by "Build release zip" action.
### Is your enhancement related to a problem? Please describe.

We are currently running E2E tests by installing dependencies and building plugin files. This is not the most accurate plugin build that will be shipped during the release. To make E2E tests more accurate and match the plugin build with the release build generated by our [deploy action](https://github.com/10up/action-wordpress-plugin-deploy), we should generate a plugin build with the "[build zip](https://github.com/10up/action-wordpress-plugin-build-zip)" action. Running E2E tests on this build will give us more accurate results.

PR for reference: https://github.com/10up/autoshare-for-twitter/pull/206

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by faisal-alvi**
### Description of the Change
PR contains changes to Run E2E tests on the zip generated by "Build release zip" action to catch release zip bugs early and at the PR level instead of manual testing before release.

Closes #126

### How to test the Change
Check the pipeline workflow results.

### Changelog Entry
Add - Run E2E tests on the zip generated by "Build release zip" action.

### Credits
Props @iamdharmesh @faisal-alvi 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by faisal-alvi** [comment]
@iamdharmesh this can not be tested until the `workflow_call` call is added in `.github/workflows/build-release-zip.yml` and this file is merged in the `develop` branch.

Workflow fail [notice](https://github.com/10up/publisher-media-kit/actions/runs/3910536647):

image

**Comment by iamdharmesh** [comment]
@faisal-alvi We can temporarily update yml file to use build-release.zip.yml from this branch (`uses: 10up/publisher-media-kit/.github/workflows/build-release-zip.yml@feat/release-e2e`). Once it passes tests we can update back to `develop`.

**Comment by faisal-alvi** [comment]
@iamdharmesh over to you!

**Review by iamdharmesh — APPROVED** [review]
Thanks for adding this @faisal-alvi. LGTM 🚀 

**Note:** I have updated the code to use build-release-zip.yml from the `develop` branch to make this PR ready for merge.

**Comment by faisal-alvi** [comment]
@jeffpaul can you please merge this PR? I can't because the `Required statuses must pass before merging`. 🚫

**Comment by jeffpaul** [comment]
I removed the required Cypress checks, but investigating the error in the latest run there: https://github.com/10up/publisher-media-kit/actions/runs/3967141149

```
Invalid workflow file: .github/workflows/cypress.yml#L14
error parsing called workflow
".github/workflows/cypress.yml"
-> "10up/publisher-media-kit/.github/workflows/build-release-zip.yml@develop" (source branch with sha:09630ac5dad1605eff0af4bfa314821641f70812)
: workflow is not reusable as it is missing a `on.workflow_call` trigger
```

**Comment by jeffpaul** [comment]
@faisal-alvi @iamdharmesh will leave it to you to help resolve what's going wrong there, but a quick comparison to the workflow file on Autoshare for Twitter (that just had a release) shows some differences that maybe we need to reflect back here?  https://github.com/10up/autoshare-for-twitter/blob/develop/.github/workflows/cypress.yml

**Comment by faisal-alvi** [comment]
@jeffpaul that error won't come after the merge. Actually it requires 'on.workflow_call' present in the yml file in the develop branch already! But actually it is being added to develop from the current PR. So as soon as we merge it, the test will find the required command and will not fail.

**Comment by jeffpaul** [comment]
Sweet, :shipit:!

**Pull request merged**
