### PR TITLE
Bump WordPress "tested up to" version 6.4

### LINKED ISSUE #170: The plugin hasn't been tested with the latest version of WordPress
There is a new WordPress version that the plugin hasn't been tested with. Please test it and then change the "Tested up to" field in the plugin readme.

**Tested up to:** 6.3
**Latest version:** 6.4

This issue will be closed automatically when the versions match.

### PR DESCRIPTION
**Pull request by jeffpaul**
### Description of the Change
This PR bumps the WP tested-up-to version 6.4 per testing results in #170.

Closes #170.

### Changelog Entry

> Changed - Bump WordPress "tested up to" version 6.4.

### Credits

Props @ankitguptaindia, @jeffpaul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
E2E tests are failing, so holding off on merging in this PR until those tests can get resolved.

**Comment by jeffpaul** [comment]
@faisal-alvi mind helping check what's going on with the tests / if additional updates are needed alongside the WP 6.4 compat bump?

**Comment by faisal-alvi** [comment]
@jeffpaul it seems related to https://github.com/10up/publisher-media-kit/pull/166, I'll try to find time to work on this, but meanwhile, any help from the 10up team would be appreciated.

**Comment by faisal-alvi** [comment]
Closing after #166

**Pull request closed without merging**
