### PR TITLE
Replace hardcoded image URLs with PUBLISHER_MEDIA_KIT_URL.

### LINKED ISSUE #111: Images not displayed when WordPress is installed in a subdirectory
### Describe the bug

As reported on [WordPress.org](https://wordpress.org/support/topic/images-not-displayed-when-wordpress-is-installed-in-a-folder/), if a WordPress install is set up in a subdirectory, the images don't work. The issue here is we have hardcoded image paths that point directly to `/wp-content`. If a site is installed in a subdirectory, this results in images not working because the subdirectory path isn't added to those images.

### Steps to Reproduce

1. Set up a new WordPress site in a subdirectory
2. Install and activate this plugin
3. Check the Media Kit page and see broken images

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by peterwilsoncc**
### Description of the Change

Updates hard coded image URLs in page template to use the `PUBLISHER_MEDIA_KIT_URL` constant defined in the main plugin file. This ensures that the images of the generated pages are correctly referenced no matter the file structure of the site. This allows for:

* WordPress installed in sub-directories such as example.com/blog
* WordPress installs using a custom content directory such as `/content`.

Closes #111

### How to test the Change

1. Install WordPress as you normally would
2. Rename the `wp-content` directory to `content`
3. Add the following to your `wp-config.php` file (replacing the values if they already exist):
   ```php
   // ========================
   // Custom Content Directory
   // ========================
   define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/content' );
   define( 'WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/content' );
   ```
4. If you already have a media kit page created by PMK, trash it.
5. Deactivate and reactivate the plugin
6. On `develop` the images will be broken, on this branch the images will display as expected.

### Changelog Entry

> Fixed - Image display on WordPress installs with non-standard content paths.

### Credits

Props @peterwilsoncc, @dkotter, @adriantry

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by faisal-alvi — APPROVED** [review]

**Comment by faisal-alvi** [comment]
@peterwilsoncc thanks for the fix. I tested the PR in a multisite setup and its working as expected. 🚀

**Comment by faisal-alvi** [comment]
@peterwilsoncc while working on #105, I've realized that we are ultimately removing the usage of plugin images and instead using third-party image URLs (something like https://upload.wikimedia.org...), so I think we won't require the current PR changes?

**Comment by peterwilsoncc** [comment]
I'd suggest retaining the images in the plugin if possible with the image licensing. 

The additional HTTP & DNS connections will be a minor performance hit to sites and it removes the risk of broken images if wikimedia is blocked.

**Comment by faisal-alvi** [comment]
Correct @peterwilsoncc, actually we are using third party image URLs because we want to submit those block patterns to the core's public block pattern library, and there only direct image links would work.

However to avoid performance issues, we can keep using our old images from plugin assets and while submitting to core, replace it with the third party direct URLs/links. Cc: @jeffpaul

**Comment by peterwilsoncc** [comment]
Gotcha, that makes sense re the pattern directory. 

I'm happy if you close this off to avoid the maintenance burden of using different images depending on the source of the pattern. I'll let you and Jeff decide though.

**Comment by jeffpaul** [comment]
@faisal-alvi can we reference direct image links from a specific tag here in the repo?

**Comment by faisal-alvi** [comment]
@jeffpaul I think I didn't understand your question. Do we need to create a variable that detects the platform (i.e. WordPress or not)? And if the platform is WordPress, we load images from the assets folder otherwise we use direct/third-party image links?

**Comment by jeffpaul** [comment]
Never mind, please proceed, thanks!

**Comment by jeffpaul** [comment]
@faisal-alvi will leave up to you on merging this in to be part of 1.3.1 or handle post-release?

**Review by faisal-alvi — APPROVED** [review]
@peterwilsoncc Thank you for your efforts.

The #105 has been closed, allowing us to move forward with this PR and merge it.

**Pull request merged**
