### PR TITLE
Add mobile styling and fix linting errors

### LINKED ISSUE #41: Our rates section should be responsive in mobile screen
**Describe the bug**
Our rates section should be responsive on mobile screen.
mobile viewport - (320*568)

**Steps to Reproduce**
-Go to Media Kit page
- Scroll down

**Expected behavior**
- Frontend should be match with design

**Screenshots**
https://www.screencast.com/t/HxT5mmqgQ

**Environment information**

Device: MacBook
OS: 12.0.1
Browser and version: Chrome 96.0.4664.55, Safari 15.1
WordPress version: 5.8.2
Theme and version: Twenty Twenty-OneVersion: 1.4 , NewspackVersion: 1.54.0-alpha.1 ,
Newspack JosephVersion: 1.53.2
** Site Helth Info**

### PR DESCRIPTION
**Pull request by godleman**
Fix https://github.com/10up/publisher-media-kit/issues/41

Adjustments to design to reduce font sizes, fix overflow issues and switch the active tab highlight to above rather than below the tab, to avoid obscuring the overflow scrollbar.

https://user-images.githubusercontent.com/55838845/156759236-ae1657b4-152e-401a-beeb-47901e8fd9f6.mp4

### CODE REVIEW

**Comment by faisal-alvi** [comment]
@cldhmmr Is this something that should be fixed in the upstream?
https://github.com/10up/block-library/tree/develop/includes/blocks/block-editor/blocks/tabs?
cc: @jeffpaul

**Comment by godleman** [comment]
> @cldhmmr Is this something that should be fixed in the upstream? https://github.com/10up/block-library/tree/develop/includes/blocks/block-editor/blocks/tabs? cc: @jeffpaul

I think it's a good point to raise thanks @faisal-alvi 
Designers will design responsive component behaviour in different ways. So there is an argument not to have any responsiveness baked into the raw tab component. In this context it needed adding to fix this UX issue.

**Review by faisal-alvi — CHANGES_REQUESTED** [review]
Thank you @cldhmmr, changes look good and the issue seems resolved.

1. However, I have seen that the thick border was at the bottom earlier but with this PR, it is now displaying at the top.

image
[image link](https://www.screencast.com/t/qllQ7rsfG)

2. (Nice to have) can we bring the "Digital Ad Specs" to a separate line for mobile devices?

image
[image link](https://www.screencast.com/t/u73KBGquom)

**Comment by godleman** [comment]
> Thank you @cldhmmr, changes look good and the issue seems resolved.
> 
> 1. However, I have seen that the thick border was at the bottom earlier but with this PR, it is now displaying at the top.
> 
> image [image link](https://www.screencast.com/t/qllQ7rsfG)
> 
> 2. (Nice to have) can we bring the "Digital Ad Specs" to a separate line for mobile devices?
> 
> image [image link](https://www.screencast.com/t/u73KBGquom)

@faisal-alvi thanks for the feedback. 
1 - that's right, I added that decision in the PR comment :
> Adjustments to design to reduce font sizes, fix overflow issues and switch the active tab highlight to above rather than below the tab, to avoid obscuring the overflow scrollbar.

2 - that would be possible in theory - having the title of the table above the tabs on mobile. @jeffpaul to advise if desired.

Thanks

**Comment by jeffpaul** [comment]
@faisal-alvi for (2) are you saying that the tab block title should be the row above the tabs on mobile view?

**Comment by faisal-alvi** [comment]
@jeffpaul yes

**Comment by jeffpaul** [comment]
Hmm, yeah I could see that being helpful on mobile @cldhmmr if you're able to handle that?

**Comment by godleman** [comment]
@jeffpaul @faisal-alvi absolutely, I'll let you know once updated

**Comment by faisal-alvi** [comment]
@cldhmmr just noting this seems to be the only PR pending before the next plugin release.

**Review by faisal-alvi — CHANGES_REQUESTED** [review]
@cldhmmr as discussed, the tab block title should be the row above the tabs on the mobile view.

**Comment by treykane** [comment]
@jeffpaul  @faisal-alvi   I've made the update in the change request here.  Additionally I noted that in some cases we were displaying the list bullets alongside the tabs.  So I ensured those were hidden as well.  Happy to help with anything further here let me know! 

Small Screen
Screen Shot 2022-04-15 at 10 43 33 AM

Medium & Up
Screen Shot 2022-04-15 at 10 43 41 AM

**Review by faisal-alvi — APPROVED** [review]
@cldhmmr @treykane thank you for your work! ❤️

**Pull request merged**
